#spring配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 105293
    url: jdbc:mysql://localhost:3306/studentmanager?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    mode: html
    prefix: classpath:/templates/
    cache: false
#拦截静态资源
#  mvc:
#    static-path-pattern: /static/**

#mybatis配置资源
mybatis:
  type-aliases-package: com.mzl.studentmanagesystem.entity
  mapper-locations: classpath:mapper/*.xml

#配端口号
server:
  port: 8080
